[build]
  command = "npm run build"
  publish = "dist"

# Only if using client-side routing (React Router, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
